name: iod

channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=10.0.130=0
  - python=3.7
  - pytorch=1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - torchvision==0.5.0
  - opencv
  - tqdm
  - pandas
  - scipy
  - tensorboard
  - scikit-learn
  - matplotlib
  - ipdb
  - pip
  - pip:
    - fvcore==0.1.1.dev200512
    - cython
